services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.hahn1.one"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 127.0.0.1:8001:80
