services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    ports:
      - "127.0.0.1:5230:5230"
    volumes:
      - ./memos-data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230
    restart: unless-stopped
