services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    networks:
        - caddy
    labels:
      caddy: stack.hahn1.one
      caddy.reverse_proxy: "{{upstreams 5001}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/data/dockge:/app/data
      - /root/stacks:/root/stacks
    environment:
      - DOCKGE_STACKS_DIR=/root/stacks

networks:
  caddy:
    external: true
